In [1]:
import numpy as np

# Manipulation Datanumbers

In [18]:
ex_array = np.array([1,2,3,4])
ex_item = 0.45

### Creation of Matrix 

In [15]:
narray = np.full((2,6), ex_item)

In [16]:
narray

array([[0.45, 0.45, 0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45, 0.45, 0.45]])

### Reshape

In [5]:
narray.reshape(6,2)

array([[0.45, 0.45],
       [0.45, 0.45],
       [0.45, 0.45],
       [0.45, 0.45],
       [0.45, 0.45],
       [0.45, 0.45]])

### Trasnform Matriz in Array

In [7]:
narray.ravel()

array([0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45,
       0.45])

### Math Operation

In [23]:
# ARRAY (+, -, *, or /) = operation applied to all items in the array
op = (ex_array+2, ex_array-2, ex_array*2, ex_array/2)
ex_array

array([1, 2, 3, 4])

In [22]:
for c in op:
    print(c)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


### Logic Operation

In [45]:
ex_array

array([1, 2, 3, 4])

In [41]:
l_op = [ex_array > 1, ex_array == 1, ex_array[ex_array == 1], 
np.mean(ex_array), ex_array[np.where(ex_array > 1)], ex_array.shape]

In [44]:
l_op

[array([False,  True,  True,  True]),
 array([ True, False, False, False]),
 array([1]),
 2.5,
 array([2, 3, 4]),
 (4,)]

In [40]:
# Examples:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[np.where(arr % 2 != 0)] = -1 
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Array Manipulation

In [46]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.array([1, 1, 1])
print(np.vstack((c,a,b)))

[[1 1 1]
 [1 2 3]
 [2 3 4]]


In [48]:
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [2, 3, 4]])

In [49]:
type(c)

numpy.ndarray

In [50]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [ ]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.append(a, b) 

In [51]:
a = np.array( [[1,2,3], [4,5,6]] )
b = np.array([2,3,4])
np.append(a, b) 

array([1, 2, 3, 4, 5, 6, 2, 3, 4])

In [52]:
b.shape

(3,)

In [53]:
a = np.array( [[1,2,3], [4,5,6]] )
b = np.array([[2,3,4], [1,1,1]])
np.append(a, b, axis=1)

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 1, 1, 1]])

In [54]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
array2D_1 = array.reshape((3,3))
array2D_2 = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18]).reshape((3,3))

In [55]:
# concatenação vertical
np.concatenate((array2D_1, array2D_2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [56]:
# concatenação horizontal
np.concatenate((array2D_1,array2D_2),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [57]:
# E como concatenar mais de 2 arrays
np.concatenate((array2D_1, array2D_2, array2D_1, array2D_1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [71]:
#Ex2: Empilhe as  matrizes a e b verticalmente
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.vstack((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#Ex3: Extraia os itens em comum entre a e b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.unique(a[np.where(a == b)])

### Math Functions 

In [64]:
# Média
np.mean( [1,2,3,4] )

2.5

In [63]:
# Desvio Padrão
np.std([1,2,3,4])

1.118033988749895

In [62]:
#mediana
np.median([1,2,3,4])

2.5

In [61]:
# np.arange
x = np.arange(start=1, stop=20, step=2) #as 3 opçoes do arange
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [60]:
np.random.shuffle(x)
print(x)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [59]:
# np.linspace
np.linspace(start=1, stop=10, num=50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [58]:
# np.where 
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
#Ex4: Imprima ou mostre apenas 3 casas decimais da matriz numpy rand_arr
rand_arr = np.random.random((5,3))
np.around(rand_arr, 3)

array([[0.396, 0.261, 0.35 ],
       [0.877, 0.876, 0.968],
       [0.988, 0.761, 0.587],
       [0.801, 0.8  , 0.473],
       [0.325, 0.672, 0.956]])

### Math Operation in between Arrays

In [139]:
array1 = np.arange(9)
array2 = np.arange(9)

In [140]:
# Soma
print(array1 + array2)

[ 0  2  4  6  8 10 12 14 16]


In [141]:
# Subtração
array1 - array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [142]:
# Divisão
array1/array2

C:\Users\georg\AppData\Local\Temp/ipykernel_22352/1676965899.py:2: RuntimeWarning: invalid value encountered in true_divide
  array1/array2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [143]:
# Multiplicação
array1*array2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

### Get Datanumbers

In [147]:
#Ex5: Importando um conjunto de dados com números e textos mantendo o texto intacto em python numpy:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [149]:
iris[0:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [152]:
sepallength[0:3]

array([5.1, 4.9, 4.7])

In [153]:
names

('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')